### PR TITLE
docs(api): correct the default type of direction in chinese docs

### PR DESCRIPTION
**Pull request by chouchouji**

### CODE REVIEW

**Comment by Alfred-Skyblue** [comment]
Thank you for the correction.

**Comment by chouchouji** [comment]
> Thank you for the correction.

No problem, I like it. I want to make it better with you if you do not mind.

**Comment by Alfred-Skyblue** [comment]
That's wonderful.

**Comment by chouchouji** [comment]
> That's wonderful.

If you need fix issues、add features or refactor code,  i will try my best. Please @ me.

**Comment by Alfred-Skyblue** [comment]
Great, thank you for being willing to work together to make this project even better!

**Pull request merged**
