### PR TITLE
feat: adding support to multi drag - First-time Contributor: Chinese Translation Assistance Needed

### PR DESCRIPTION
**Pull request by matheus-foscarinid**
This is my first pull request to an open-source project. It implements #14,  the **multiDrag** feature for the component, which allows users to drag multiple items at the same time.

I would appreciate any assistance in adding the Chinese translation to this project. Unfortunately, I don't have the knowledge to complete the translation myself. 

Thank you for the consideration.

### CODE REVIEW

**Comment by Alfred-Skyblue** [comment]
It seems like it only updates the position of the DOM elements and doesn't change the positions of multiple arrays. What should we do in the `onUpdate` function to update the positions of multiple elements using `newIndices` and `oldIndices`?

**Comment by matheus-foscarinid** [comment]
> It seems like it only updates the position of the DOM elements and doesn't change the positions of multiple arrays. What should we do in the `onUpdate` function to update the positions of multiple elements using `newIndices` and `oldIndices`?

You're right, it's not updating the list correctly, I'll be trying to fix this problem. 

I've done some updates to the multi drag `onUpdate`, but for now in some cases it is not updating correctly the items as it should be, in some cases the order is not correct. I'll be back with this feat working, thanks.

**Comment by matheus-foscarinid** [comment]
You're completely right, @Alfred-Skyblue . I've been trying to fix the ordering and currently the array is being ordered correctly, but the list items in some cases are messed up. Before trying some alternatives I'd like to ask you about the `onUpdate` code:

```
const { from, item, oldIndex, newIndex } = evt
removeNode(item)
insertNodeAt(from, item, oldIndex!)
moveArrayElement(unref(list), oldIndex!, newIndex!)
```

I've noticed that the `insertNodeAt` function re-add the element in its old position. Is this the expected behavior, and have I missed something? cause probably I'm trying to implement without considering some rule.

**Comment by AhmedEaswy** [comment]
why dose not any one merged it ?

**Comment by oemer-aran** [comment]
I am also wondering why the progress here was stopped? It's such a valuable feature. Vue Draggable Plus seems to be best drag and drop library for vue 3 (I tried many) and it would be great if we could have multi drag!

**Pull request closed without merging**
