### PR TITLE
feat: check if element  existed when move between groups

### PR DESCRIPTION
**Pull request by solarcellsky**
Sometimes we need to check the element  existed when move element between groups. So i made this PR.

### CODE REVIEW

**Comment by solarcellsky** [comment]
I modified onAdd and onRemove function, add an attribute 'existed' for element in onAdd function. In onRemove function check this attribute, if existed the element will not moved to 'to' target and will kept in 'from' target.

**Comment by Alfred-Skyblue** [comment]
Are you dealing with a case where an element needs to exist in multiple groups simultaneously?

**Comment by solarcellsky** [comment]
> Are you dealing with a case where an element needs to exist in multiple groups simultaneously?

Yes. I have been working on a module about scheduling recently, which is divided into different shifts and shifts, and these plans may be repeated, but the dates are different, and most of the personnel say that the time is fixed, but they are on duty at different times and shifts, so there must be duplication, and my need is to adjust by dragging the list of these personnel. The whole schedule plan, this is my practical application scenario.

**Comment by Alfred-Skyblue** [comment]
I don't think this is an issue that needs to be handled by vue-draggable-plus, because if my array elements are primitive types, for example:

```js
const list1 = [1, 2, 3, 4];

const list2 = [2, 3, 4, 5];
```

Then it is very clear that 2, 3, and 4 are duplicates. However, dragging between groups is allowed. You can try using `filter` to disable the dragging of elements that already exist in `list2`, instead of prohibiting the dragging of identical elements between multiple lists.

**Comment by solarcellsky** [comment]
https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/546897/e1e97d8d-c6f9-4e7b-9fbd-441022e5045b

There is a screen record to show how i use vue-draggable-plus. Maybe my needs are not common. Thank you for your patient reply.

**Comment by Alfred-Skyblue** [comment]
Thank you for your PR. I believe this requirement is quite uncommon, so we are not planning to implement this feature for now.

**Pull request closed without merging**
